### PR TITLE
Merge pull request #1 from eLunate/master

### PR DESCRIPTION
**Pull request by NovusTheory**
Merge latest version

### CODE REVIEW

**Comment by eLunate** [comment]
Eh what? I'm not sure exactly what you're doing with this here.

**Comment by NovusTheory** [comment]
Nothing xD. Was trying to update my side. lel fail

**Comment by eLunate** [comment]
You nut.

**Comment by NovusTheory** [comment]
ye. While I'm at it. Might as well add the ability for people to create custom Status/Vitals. Y U NO ADD THEM YET

**Comment by eLunate** [comment]
Well, you can, obviously. It's open source just edit the code; I'm not going to add an API for adding them, because there's not a standard way to handle them.

**Comment by NovusTheory** [comment]
Oh, I'll add it once I study your code to figure out what's going on. Course the user will provide a function to control what happens to the custom Status/Vital. Might not be a good idea?

**Comment by eLunate** [comment]
Well, you're looking at the small problem of how they handle the hooks, especially from the other components. Does the Vital/Status have special Mods from Status? Do they have special modifier hooks for items and other Status effects? Are they affected by being OverEncumbered?

**Pull request closed without merging**
